import os from 'node:os';
import path from 'node:path';
import { engineStopMs } from './shutdown.js';
import { writablePaths } from './config.js';

/**
 * A unit file written from the configuration it will run.
 *
 * Every failure this project has diagnosed under systemd came from the unit
 * and the configuration disagreeing, and none of them looked like what they
 * were:
 *
 *   - a `savePath` missing from `ReadWritePaths` fails inside the unit's
 *     namespace, before any permission bit is read, so the directory's owner
 *     and mode are both perfect and the write is still refused
 *   - the default `KillMode` signals the Python sidecar at the same instant as
 *     the node, so the sidecar dies before it can write resume data and every
 *     archive returns at 0% to be re-checked
 *   - a `TimeoutStopSec` shorter than the resume save kills the process
 *     mid-write, which costs the same re-check by a different route
 *   - libuv's thread pool holds four threads unless the unit says otherwise,
 *     so a `stacks.bakeConcurrency` above four exports at a fraction of the
 *     machine with every core idle, no error, and nothing in the journal
 *
 * None of that is discoverable from the symptom. All of it is decidable from
 * the configuration, which is why this is generated rather than documented.
 */

/** What the resume save can want, before the library has grown into it. */
export const TIMEOUT_STOP_SECONDS = 300;

/**
 * How long systemd should allow a stop, for a library of this size.
 *
 * The node gives its engine two seconds an archive to write resume data, and
 * systemd's allowance has to outlast that or the save is cut off partway --
 * which is exactly the library that returns at 0% and re-hashes for hours.
 * A fixed five minutes covered a library of 145 and no more, silently, so
 * this is derived the same way `ReadWritePaths` and the thread pool are.
 *
 * Rounded up to whole minutes, with a wide margin over the node's own budget:
 * being generous here costs nothing, since systemd stops waiting the moment
 * the process is gone.
 * @param {object} config - The resolved configuration.
 * @param {number} [archives] - How many the catalog holds.
 * @returns {number} - Seconds for `TimeoutStopSec`.
 */
export function stopTimeoutFor(config, archives = 0) {
  const budget = engineStopMs(archives) / 1000;
  const wanted = Math.ceil((budget * 1.5 + 60) / 60) * 60;
  return Math.max(TIMEOUT_STOP_SECONDS, wanted);
}

/** libuv's own, which is what a unit that says nothing gets. */
const DEFAULT_THREADPOOL = 4;

/**
 * How many threads sharp gets, which is what an export is really limited by.
 *
 * Derived rather than left to the operator for the same reason as
 * `ReadWritePaths`: it is decidable from the configuration, and getting it
 * wrong produces no error at all — just an export running at a fraction of the
 * machine, with every core idle and nothing in the journal.
 *
 * Capped at the core count of the machine this is generated on, because past
 * that a thread has nowhere to run and the measured throughput flattens. Never
 * below libuv's own four, so the unit cannot ask for less than saying nothing
 * would have given it.
 * @param {object} config - The resolved configuration.
 * @returns {number} - What to put in the unit.
 */
function threadPoolFor(config) {
  const bake = Number(config?.stacks?.bakeConcurrency) || DEFAULT_THREADPOOL;
  const useful = Math.min(Math.floor(bake), os.availableParallelism());
  return Math.max(DEFAULT_THREADPOOL, useful);
}

/**
 * The unit file for a configuration.
 * @param {object} options - What to write.
 * @param {object} options.config - The resolved configuration.
 * @param {string} options.configPath - Where that configuration lives.
 * @param {string} [options.user] - Service account. Default 'pmtiles-swarm'.
 * @param {string} [options.execStart] - The binary. Default the documented install.
 * @param {string} [options.workingDirectory] - Default the binary's install root.
 * @returns {string} - The unit, ready to install.
 */
export function unitFor({
  config,
  configPath,
  user = 'pmtiles-swarm',
  execStart,
  workingDirectory,
  archives = 0,
}) {
  const home = workingDirectory ?? `/var/lib/${user}`;
  const binary = execStart ?? `${home}/node_modules/.bin/pmtiles-swarm`;
  const paths = writablePaths(config, configPath);
  const threadPool = threadPoolFor(config);
  const stopSeconds = stopTimeoutFor(config, archives);

  // Wrapped the way systemd's own examples are, because this list grows with
  // every watched folder and a single line of them is unreadable in a diff.
  const readWrite = paths.join(' \\\n  ');

  return `# pmtiles-swarm, generated by \`pmtiles-swarm init --systemd\`.
#
# Install it, then check what systemd actually merged — which is the only
# account of it worth trusting:
#
#   sudo cp pmtiles-swarm.service /etc/systemd/system/
#   sudo systemctl daemon-reload
#   sudo systemctl enable --now pmtiles-swarm
#   systemctl show -p ReadWritePaths -p KillMode -p TimeoutStopUSec pmtiles-swarm
#
# ReadWritePaths below was derived from ${path.basename(configPath)}. Adding a
# watched folder, a subscription with its own save path, or a cache directory
# to that file means adding it here too — or the write is refused with the
# directory's permissions perfect. Re-running init --systemd rewrites this.

[Unit]
Description=pmtiles-swarm
Documentation=https://github.com/TechIdiots-LLC/pmtiles-swarm
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${user}
Group=${user}

WorkingDirectory=${home}

# Absolute: systemd reads no shell profile.
ExecStart=${binary} \\
  --config ${path.resolve(configPath)}

# How many tiles a stack export can decode or encode at once. That work is
# sharp, sharp does it on libuv's thread pool, and the pool holds four threads
# unless this says otherwise — so without it, stacks.bakeConcurrency above four
# moves where the merges queue rather than how many of them run, and the export
# is several times slower than the machine with nothing to show why. Set from
# stacks.bakeConcurrency (${threadPool}); it cannot be set from inside the process.
Environment=UV_THREADPOOL_SIZE=${threadPool}

# Required, not a preference. The console's Save & Restart applies settings a
# running process cannot take, so it exits 0 and expects to be brought back;
# Restart=on-failure ignores an exit 0 and would leave the node stopped with
# the unit reporting success.
Restart=always
RestartSec=5

# Stopping writes resume data for every archive, and the node allows its engine
# two seconds per torrent to do it. This has to outlast that: killed mid-save,
# every archive that had not been written re-hashes its whole store on the way
# back up, which for a 700 GiB archive is hours.
#
# Derived from the ${archives} archive(s) this node holds, with room to grow.
# A fixed five minutes covered a library of 145 and no more, and covered it
# silently — the symptom of outgrowing it is not an error but a library that
# comes back at 0%. Re-running init --systemd recomputes this;
# tools/resume-doctor.py prints the arithmetic for yours.
TimeoutStopSec=${stopSeconds}

# The node stops the sidecar itself, and needs it alive to do so. The default,
# control-group, signals both at once and the sidecar dies before it can write
# anything. That is what a library returning at 0% after every restart is.
KillMode=mixed

# A seeding node holds a socket per peer, and the tile reader holds file
# descriptors of its own.
LimitNOFILE=65535

# Everything not named below is read-only inside this unit's namespace.
ProtectSystem=strict
ProtectHome=read-only
PrivateTmp=true
NoNewPrivileges=true

ReadWritePaths=${readWrite}

# Group-writable, so what this service creates in a folder shared with whatever
# builds the archives can still be modified by it.
UMask=0002

[Install]
WantedBy=multi-user.target
`;
}

/**
 * The commands that make the directories this unit needs, owned correctly.
 *
 * Printed rather than run. init may be running as root or as a person, and a
 * directory created by the wrong one is the same refused write as a missing
 * `ReadWritePaths` entry — with even less to go on, because the unit is right.
 * @param {object} options - What to write.
 * @param {object} options.config - The resolved configuration.
 * @param {string} options.configPath - Where that configuration lives.
 * @param {string} [options.user] - Service account.
 * @returns {string[]} - Shell commands, in the order they should be run.
 */
export function directoryCommands({
  config,
  configPath,
  user = 'pmtiles-swarm',
}) {
  // The config's own directory is excluded: it exists already, since the file
  // was just written into it, and it is usually /etc where this would be wrong.
  const configDir = path.dirname(path.resolve(configPath));
  const wanted = writablePaths(config, configPath).filter(
    (value) => value !== configDir,
  );

  return [
    `sudo useradd --system --home-dir /var/lib/${user} --shell /usr/sbin/nologin ${user}`,
    ...wanted.map(
      (value) => `sudo install -d -o ${user} -g ${user} -m 0775 ${value}`,
    ),
    // The directory as well as the file. The console rewrites the
    // configuration by writing a temp file beside it and renaming, which needs
    // write permission on the directory rather than on the file.
    `sudo chown ${user} ${configDir} ${path.resolve(configPath)}`,
  ];
}
